# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_raspberry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='temperature',
            field=models.CharField(max_length=4),
        ),
    ]
