# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160805_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
